### ISSUE TITLE
Tạo trang đăng kí

### ISSUE THREAD

**Issue by NgocNhanUIT** [thanhstar260/CNPM#21]

**Comment by thanhstar260** [comment]
done

**Comment by thanhstar260** [comment]
Commit :
https://github.com/thanhstar260/CNPM/commit/85e72070f2ea8716d1b00ff40281fc452f6e1e19
https://github.com/thanhstar260/CNPM/commit/32f46d74279632c50eb46fb9c88f0d395601384d
https://github.com/thanhstar260/CNPM/commit/feb6a74fef6994b20ee50d64338a0734068b7c76
https://github.com/thanhstar260/CNPM/commit/da8d09408cba586f8899028f7f81b3015923c117
https://github.com/thanhstar260/CNPM/commit/0244173d4d738da114947b6676bc108adfe9e3bc
