### ISSUE TITLE
Thêm tính năng lọc sách theo giá

### ISSUE THREAD

**Issue by NgocNhanUIT** [thanhstar260/CNPM#24]

**Comment by NgocNhanUIT** [comment]
done

**Comment by thanhstar260** [comment]
Commit :
https://github.com/thanhstar260/CNPM/commit/3cce29ac4517ec2dc557cfe121328e94363bbebc
https://github.com/thanhstar260/CNPM/commit/2f3302fc68bd003e249ceb9586bfdc69945d5bfa
